version: "3"

services:
 demoapp:
  image: $WEB_IMAGE_NAME
  deploy:
   replicas: 2
   labels:
    - "traefik.backend=demoapp"
    - "traefik.port=8080"
    - "traefik.frontend.rule=Host:demoapp.westeurope.cloudapp.azure.com"
networks:
 default:
  external:
   name: traefik-net

