########################################################################
# BUILDER CONTAINER

# Set up build environment
FROM maven:3-jdk-8-alpine as builder
WORKDIR /src
COPY pom.xml ./
COPY src ./src/

# Build project using Maven
RUN mvn package

########################################################################
# APPLICATION CONTAINER

# Use a standard library WildFly image
#FROM jboss/wildfly:8.2.1.Final
#FROM jboss/wildfly:9.0.2.Final
FROM jboss/wildfly:10.1.0.Final

# Deploy the application using the WAR file generated by the builder container
COPY --from=builder /src/target/demo.war /opt/jboss/wildfly/standalone/deployments/
